### ISSUE TITLE
TODO's

### ISSUE THREAD

**Issue by shreya-mishra** [shreya-mishra/google-keep#2]
**P3 Functionality**

- [ ] multi line description
- [ ] in ever modal we should have close functionality
- [ ] If more words it should say read more... which should be expandable in a modal , in P4 -> we can give `task detail page` 
- [ ] It should have save draft feature as well to which we can edit in future
- [ ] in P4-  it should have `notes` and `draft` section
